[workspace]
members = [
    "crates/rhsp3_internal_plugabi",
    "crates/rhsp3_plugsdk",
]

[profile.dev]
opt-level = "s"
lto = false
panic = "abort"

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
