[package]
name = "rhsp3_plugsdk"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8.31"
log = "0.4.17"
parking_lot = { version = "0.12.1", features = ["hardware-lock-elision"] }

rhsp3_common = { path = "../rhsp3_common" }
rhsp3_internal_abi = { path = "../rhsp3_internal_abi" }
