/* automatically generated by rust-bindgen 0.61.0 */

pub const HSPVAR_FLAG_NONE: u32 = 0;
pub const HSPVAR_FLAG_LABEL: u32 = 1;
pub const HSPVAR_FLAG_STR: u32 = 2;
pub const HSPVAR_FLAG_DOUBLE: u32 = 3;
pub const HSPVAR_FLAG_INT: u32 = 4;
pub const HSPVAR_FLAG_STRUCT: u32 = 5;
pub const HSPVAR_FLAG_COMSTRUCT: u32 = 6;
pub const HSPVAR_FLAG_USERDEF: u32 = 8;
pub const HSPVAR_FLAG_MAX: u32 = 8;
pub const HSPVAR_MODE_NONE: i32 = -1;
pub const HSPVAR_MODE_MALLOC: u32 = 1;
pub const HSPVAR_MODE_CLONE: u32 = 2;
pub const HSPVAR_SUPPORT_STORAGE: u32 = 1;
pub const HSPVAR_SUPPORT_FLEXSTORAGE: u32 = 2;
pub const HSPVAR_SUPPORT_FIXEDARRAY: u32 = 4;
pub const HSPVAR_SUPPORT_FLEXARRAY: u32 = 8;
pub const HSPVAR_SUPPORT_ARRAYOBJ: u32 = 16;
pub const HSPVAR_SUPPORT_FLEXSIZE: u32 = 32;
pub const HSPVAR_SUPPORT_NOCONVERT: u32 = 64;
pub const HSPVAR_SUPPORT_VARUSE: u32 = 128;
pub const HSPVAR_SUPPORT_TEMPVAR: u32 = 256;
pub const HSPVAR_SUPPORT_USER1: u32 = 16384;
pub const HSPVAR_SUPPORT_USER2: u32 = 32768;
pub const HSPVAR_SUPPORT_MISCTYPE: u32 = 16;
pub const FLEXVAL_TYPE_NONE: u32 = 0;
pub const FLEXVAL_TYPE_ALLOC: u32 = 1;
pub const FLEXVAL_TYPE_CLONE: u32 = 2;
pub const HSP3DEBUG_MODULE: &[u8; 10usize] = b"hsp3debug\0";
pub const HSP3DEBUG_INIT: &[u8; 9usize] = b"debugini\0";
pub const HSP3DEBUG_NOTICE: &[u8; 13usize] = b"debug_notice\0";
pub const TYPE_MARK: u32 = 0;
pub const TYPE_VAR: u32 = 1;
pub const TYPE_STRING: u32 = 2;
pub const TYPE_DNUM: u32 = 3;
pub const TYPE_INUM: u32 = 4;
pub const TYPE_STRUCT: u32 = 5;
pub const TYPE_XLABEL: u32 = 6;
pub const TYPE_LABEL: u32 = 7;
pub const TYPE_INTCMD: u32 = 8;
pub const TYPE_EXTCMD: u32 = 9;
pub const TYPE_EXTSYSVAR: u32 = 10;
pub const TYPE_CMPCMD: u32 = 11;
pub const TYPE_MODCMD: u32 = 12;
pub const TYPE_INTFUNC: u32 = 13;
pub const TYPE_SYSVAR: u32 = 14;
pub const TYPE_PROGCMD: u32 = 15;
pub const TYPE_DLLFUNC: u32 = 16;
pub const TYPE_DLLCTRL: u32 = 17;
pub const TYPE_USERDEF: u32 = 18;
pub const TYPE_ERROR: i32 = -1;
pub const TYPE_CALCERROR: i32 = -2;
pub const PARAM_OK: u32 = 0;
pub const PARAM_SPLIT: i32 = -1;
pub const PARAM_END: i32 = -2;
pub const PARAM_DEFAULT: i32 = -3;
pub const PARAM_ENDSPLIT: i32 = -4;
pub const HSP3_FUNC_MAX: u32 = 18;
pub const HSP3_TYPE_USER: u32 = 18;
pub const EXFLG_0: u32 = 4096;
pub const EXFLG_1: u32 = 8192;
pub const EXFLG_2: u32 = 16384;
pub const EXFLG_3: u32 = 32768;
pub const CSTYPE: u32 = 4095;
pub const HSPHED_BOOTOPT_DEBUGWIN: u32 = 1;
pub const HSPHED_BOOTOPT_WINHIDE: u32 = 2;
pub const HSPHED_BOOTOPT_DIRSAVE: u32 = 4;
pub const HSPHED_BOOTOPT_SAVER: u32 = 256;
pub const HSPHED_BOOTOPT_RUNTIME: u32 = 4096;
pub const HSPHED_BOOTOPT_NOMMTIMER: u32 = 8192;
pub const HSPHED_BOOTOPT_NOGDIP: u32 = 16384;
pub const HSPHED_BOOTOPT_FLOAT32: u32 = 32768;
pub const HSPHED_BOOTOPT_ORGRND: u32 = 65536;
pub const HSPHED_BOOTOPT_UTF8: u32 = 131072;
pub const HSPHED_BOOTOPT_HSP64: u32 = 262144;
pub const HSPHED_BOOTOPT_IORESUME: u32 = 524288;
pub const HPIDAT_FLAG_TYPEFUNC: u32 = 0;
pub const HPIDAT_FLAG_SELFFUNC: i32 = -1;
pub const HPIDAT_FLAG_VARFUNC: u32 = 1;
pub const HPIDAT_FLAG_DLLFUNC: u32 = 2;
pub const HSPHED_EXOPTION_TAG_NONE: u32 = 0;
pub const HSPHED_EXOPTION_TAG_DSINDEX: u32 = 1;
pub const HSPHED_EXOPTION_TAG_SIZEX: u32 = 2;
pub const HSPHED_EXOPTION_TAG_SIZEY: u32 = 3;
pub const HSPHED_EXOPTION_TAG_SYSREQ: u32 = 4;
pub const LIBDAT_FLAG_NONE: u32 = 0;
pub const LIBDAT_FLAG_DLL: u32 = 1;
pub const LIBDAT_FLAG_DLLINIT: u32 = 2;
pub const LIBDAT_FLAG_MODULE: u32 = 3;
pub const LIBDAT_FLAG_COMOBJ: u32 = 4;
pub const MPTYPE_NONE: u32 = 0;
pub const MPTYPE_VAR: u32 = 1;
pub const MPTYPE_STRING: u32 = 2;
pub const MPTYPE_DNUM: u32 = 3;
pub const MPTYPE_INUM: u32 = 4;
pub const MPTYPE_STRUCT: u32 = 5;
pub const MPTYPE_LABEL: u32 = 7;
pub const MPTYPE_LOCALVAR: i32 = -1;
pub const MPTYPE_ARRAYVAR: i32 = -2;
pub const MPTYPE_SINGLEVAR: i32 = -3;
pub const MPTYPE_FLOAT: i32 = -4;
pub const MPTYPE_STRUCTTAG: i32 = -5;
pub const MPTYPE_LOCALSTRING: i32 = -6;
pub const MPTYPE_MODULEVAR: i32 = -7;
pub const MPTYPE_PPVAL: i32 = -8;
pub const MPTYPE_PBMSCR: i32 = -9;
pub const MPTYPE_PVARPTR: i32 = -10;
pub const MPTYPE_IMODULEVAR: i32 = -11;
pub const MPTYPE_IOBJECTVAR: i32 = -12;
pub const MPTYPE_LOCALWSTR: i32 = -13;
pub const MPTYPE_FLEXSPTR: i32 = -14;
pub const MPTYPE_FLEXWPTR: i32 = -15;
pub const MPTYPE_PTR_REFSTR: i32 = -16;
pub const MPTYPE_PTR_EXINFO: i32 = -17;
pub const MPTYPE_PTR_DPMINFO: i32 = -18;
pub const MPTYPE_NULLPTR: i32 = -19;
pub const MPTYPE_TMODULEVAR: i32 = -20;
pub const STRUCTPRM_SUBID_STACK: i32 = -1;
pub const STRUCTPRM_SUBID_STID: i32 = -2;
pub const STRUCTPRM_SUBID_DLL: i32 = -3;
pub const STRUCTPRM_SUBID_DLLINIT: i32 = -4;
pub const STRUCTPRM_SUBID_OLDDLL: i32 = -5;
pub const STRUCTPRM_SUBID_OLDDLLINIT: i32 = -6;
pub const STRUCTPRM_SUBID_COMOBJ: i32 = -7;
pub const STRUCTCODE_THISMOD: i32 = -1;
pub const TYPE_OFFSET_COMOBJ: u32 = 4096;
pub const STRUCTDAT_OT_NONE: u32 = 0;
pub const STRUCTDAT_OT_CLEANUP: u32 = 1;
pub const STRUCTDAT_OT_STATEMENT: u32 = 2;
pub const STRUCTDAT_OT_FUNCTION: u32 = 4;
pub const STRUCTDAT_INDEX_FUNC: i32 = -1;
pub const STRUCTDAT_INDEX_CFUNC: i32 = -2;
pub const STRUCTDAT_INDEX_STRUCT: i32 = -3;
pub const STRUCTDAT_FUNCFLAG_CLEANUP: u32 = 65536;
pub const MODVAR_MAGICCODE: u32 = 21930;
pub const IRQ_FLAG_NONE: u32 = 0;
pub const IRQ_FLAG_DISABLE: u32 = 1;
pub const IRQ_FLAG_ENABLE: u32 = 2;
pub const IRQ_OPT_GOTO: u32 = 0;
pub const IRQ_OPT_GOSUB: u32 = 1;
pub const IRQ_OPT_CALLBACK: u32 = 2;
pub const HSP3_REPEAT_MAX: u32 = 32;
pub const HSPCTX_REFSTR_MAX: u32 = 4096;
pub const HSPCTX_CMDLINE_MAX: u32 = 256;
pub const HSPCTX_PATH_MAX: u32 = 64;
pub const HSPSTAT_NORMAL: u32 = 0;
pub const HSPSTAT_DEBUG: u32 = 1;
pub const HSPSTAT_SSAVER: u32 = 2;
pub const HSPSTAT_CONSOLE: u32 = 16;
pub const HSPSTAT_MAC: u32 = 128;
pub const HSPSTAT_DISH: u32 = 256;
pub const HSPSTAT_LINUX: u32 = 4096;
pub const HSPSTAT_UTF8: u32 = 131072;
pub const HSPSTAT_HSP64: u32 = 262144;
pub const TYPE_EX_SUBROUTINE: u32 = 256;
pub const TYPE_EX_CUSTOMFUNC: u32 = 257;
pub const TYPE_EX_ENDOFPARAM: u32 = 512;
pub const TYPE_EX_ARRAY_VARS: u32 = 513;
pub const TYPE_EX_LOCAL_VARS: u32 = 514;
pub const HSPCTX_LANGUAGE_EN: u32 = 0;
pub const HSPCTX_LANGUAGE_JP: u32 = 1;
pub const HSPEVENT_ENABLE_COMMAND: u32 = 1;
pub const HSPEVENT_ENABLE_HSPIRQ: u32 = 2;
pub const HSPEVENT_ENABLE_GETKEY: u32 = 4;
pub const HSPEVENT_ENABLE_FILE: u32 = 8;
pub const HSPEVENT_ENABLE_MEDIA: u32 = 16;
pub const HSPEVENT_ENABLE_PICLOAD: u32 = 32;
pub const GINFO_EXINFO_MAX: u32 = 16;
pub const GINFO_EXINFO_BASE: u32 = 256;
pub const GINFO_EXINFO_ACCEL_X: u32 = 256;
pub const GINFO_EXINFO_ACCEL_Y: u32 = 257;
pub const GINFO_EXINFO_ACCEL_Z: u32 = 258;
pub const GINFO_EXINFO_GYRO_X: u32 = 259;
pub const GINFO_EXINFO_GYRO_Y: u32 = 260;
pub const GINFO_EXINFO_GYRO_Z: u32 = 261;
pub type PDAT = *mut ::std::os::raw::c_void;
pub type APTR = ::std::os::raw::c_int;
pub const CALCCODE_ADD: _bindgen_ty_1 = _bindgen_ty_1(0);
pub const CALCCODE_SUB: _bindgen_ty_1 = _bindgen_ty_1(1);
pub const CALCCODE_MUL: _bindgen_ty_1 = _bindgen_ty_1(2);
pub const CALCCODE_DIV: _bindgen_ty_1 = _bindgen_ty_1(3);
pub const CALCCODE_MOD: _bindgen_ty_1 = _bindgen_ty_1(4);
pub const CALCCODE_AND: _bindgen_ty_1 = _bindgen_ty_1(5);
pub const CALCCODE_OR: _bindgen_ty_1 = _bindgen_ty_1(6);
pub const CALCCODE_XOR: _bindgen_ty_1 = _bindgen_ty_1(7);
pub const CALCCODE_EQ: _bindgen_ty_1 = _bindgen_ty_1(8);
pub const CALCCODE_NE: _bindgen_ty_1 = _bindgen_ty_1(9);
pub const CALCCODE_GT: _bindgen_ty_1 = _bindgen_ty_1(10);
pub const CALCCODE_LT: _bindgen_ty_1 = _bindgen_ty_1(11);
pub const CALCCODE_GTEQ: _bindgen_ty_1 = _bindgen_ty_1(12);
pub const CALCCODE_LTEQ: _bindgen_ty_1 = _bindgen_ty_1(13);
pub const CALCCODE_RR: _bindgen_ty_1 = _bindgen_ty_1(14);
pub const CALCCODE_LR: _bindgen_ty_1 = _bindgen_ty_1(15);
pub const CALCCODE_MAX: _bindgen_ty_1 = _bindgen_ty_1(16);
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct _bindgen_ty_1(pub ::std::os::raw::c_int);
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct PVal {
    pub flag: ::std::os::raw::c_short,
    pub mode: ::std::os::raw::c_short,
    pub len: [::std::os::raw::c_int; 5usize],
    pub size: ::std::os::raw::c_int,
    pub pt: *mut ::std::os::raw::c_char,
    pub master: *mut ::std::os::raw::c_void,
    pub support: ::std::os::raw::c_ushort,
    pub arraycnt: ::std::os::raw::c_short,
    pub offset: ::std::os::raw::c_int,
    pub arraymul: ::std::os::raw::c_int,
}
impl Default for PVal {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct HspVarProc {
    pub flag: ::std::os::raw::c_short,
    pub aftertype: ::std::os::raw::c_short,
    pub version: ::std::os::raw::c_short,
    pub support: ::std::os::raw::c_ushort,
    pub basesize: ::std::os::raw::c_short,
    pub opt: ::std::os::raw::c_short,
    pub vartype_name: *mut ::std::os::raw::c_char,
    pub user: *mut ::std::os::raw::c_char,
    pub Cnv: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            buffer: *const ::std::os::raw::c_void,
            flag: ::std::os::raw::c_int,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub CnvCustom: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            buffer: *const ::std::os::raw::c_void,
            flag: ::std::os::raw::c_int,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub GetPtr: ::std::option::Option<unsafe extern "C-unwind" fn(pval: *mut PVal) -> *mut PDAT>,
    pub ArrayObjectRead: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            pval: *mut PVal,
            mptype: *mut ::std::os::raw::c_int,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub ArrayObject: ::std::option::Option<unsafe extern "C-unwind" fn(pval: *mut PVal)>,
    pub ObjectWrite: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            pval: *mut PVal,
            data: *mut ::std::os::raw::c_void,
            type_: ::std::os::raw::c_int,
        ),
    >,
    pub ObjectMethod: ::std::option::Option<unsafe extern "C-unwind" fn(pval: *mut PVal)>,
    pub Alloc: ::std::option::Option<unsafe extern "C-unwind" fn(pval: *mut PVal, pval2: *const PVal)>,
    pub Free: ::std::option::Option<unsafe extern "C-unwind" fn(pval: *mut PVal)>,
    pub GetSize:
        ::std::option::Option<unsafe extern "C-unwind" fn(pdat: *const PDAT) -> ::std::os::raw::c_int>,
    pub GetUsing:
        ::std::option::Option<unsafe extern "C-unwind" fn(pdat: *const PDAT) -> ::std::os::raw::c_int>,
    pub GetBlockSize: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            pval: *mut PVal,
            pdat: *mut PDAT,
            size: *mut ::std::os::raw::c_int,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub AllocBlock: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PVal, pdat: *mut PDAT, size: ::std::os::raw::c_int),
    >,
    pub Set: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PVal, pdat: *mut PDAT, in_: *const ::std::os::raw::c_void),
    >,
    pub AddI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub SubI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub MulI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub DivI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub ModI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub AndI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub OrI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub XorI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub EqI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub NeI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub GtI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub LtI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub GtEqI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub LtEqI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub RrI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
    pub LrI: ::std::option::Option<
        unsafe extern "C-unwind" fn(pval: *mut PDAT, val: *const ::std::os::raw::c_void),
    >,
}
impl Default for HspVarProc {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type HSPVAR_COREFUNC = ::std::option::Option<unsafe extern "C-unwind" fn(arg1: *mut HspVarProc)>;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct FlexValue {
    pub type_: ::std::os::raw::c_short,
    pub myid: ::std::os::raw::c_short,
    pub customid: ::std::os::raw::c_short,
    pub clonetype: ::std::os::raw::c_short,
    pub size: ::std::os::raw::c_int,
    pub ptr: *mut ::std::os::raw::c_void,
}
impl Default for FlexValue {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const HSPERROR_HSPERR_NONE: HSPERROR = HSPERROR(0);
pub const HSPERROR_HSPERR_UNKNOWN_CODE: HSPERROR = HSPERROR(1);
pub const HSPERROR_HSPERR_SYNTAX: HSPERROR = HSPERROR(2);
pub const HSPERROR_HSPERR_ILLEGAL_FUNCTION: HSPERROR = HSPERROR(3);
pub const HSPERROR_HSPERR_WRONG_EXPRESSION: HSPERROR = HSPERROR(4);
pub const HSPERROR_HSPERR_NO_DEFAULT: HSPERROR = HSPERROR(5);
pub const HSPERROR_HSPERR_TYPE_MISMATCH: HSPERROR = HSPERROR(6);
pub const HSPERROR_HSPERR_ARRAY_OVERFLOW: HSPERROR = HSPERROR(7);
pub const HSPERROR_HSPERR_LABEL_REQUIRED: HSPERROR = HSPERROR(8);
pub const HSPERROR_HSPERR_TOO_MANY_NEST: HSPERROR = HSPERROR(9);
pub const HSPERROR_HSPERR_RETURN_WITHOUT_GOSUB: HSPERROR = HSPERROR(10);
pub const HSPERROR_HSPERR_LOOP_WITHOUT_REPEAT: HSPERROR = HSPERROR(11);
pub const HSPERROR_HSPERR_FILE_IO: HSPERROR = HSPERROR(12);
pub const HSPERROR_HSPERR_PICTURE_MISSING: HSPERROR = HSPERROR(13);
pub const HSPERROR_HSPERR_EXTERNAL_EXECUTE: HSPERROR = HSPERROR(14);
pub const HSPERROR_HSPERR_PRIORITY: HSPERROR = HSPERROR(15);
pub const HSPERROR_HSPERR_TOO_MANY_PARAMETERS: HSPERROR = HSPERROR(16);
pub const HSPERROR_HSPERR_TEMP_BUFFER_OVERFLOW: HSPERROR = HSPERROR(17);
pub const HSPERROR_HSPERR_WRONG_NAME: HSPERROR = HSPERROR(18);
pub const HSPERROR_HSPERR_DIVIDED_BY_ZERO: HSPERROR = HSPERROR(19);
pub const HSPERROR_HSPERR_BUFFER_OVERFLOW: HSPERROR = HSPERROR(20);
pub const HSPERROR_HSPERR_UNSUPPORTED_FUNCTION: HSPERROR = HSPERROR(21);
pub const HSPERROR_HSPERR_EXPRESSION_COMPLEX: HSPERROR = HSPERROR(22);
pub const HSPERROR_HSPERR_VARIABLE_REQUIRED: HSPERROR = HSPERROR(23);
pub const HSPERROR_HSPERR_INTEGER_REQUIRED: HSPERROR = HSPERROR(24);
pub const HSPERROR_HSPERR_BAD_ARRAY_EXPRESSION: HSPERROR = HSPERROR(25);
pub const HSPERROR_HSPERR_OUT_OF_MEMORY: HSPERROR = HSPERROR(26);
pub const HSPERROR_HSPERR_TYPE_INITALIZATION_FAILED: HSPERROR = HSPERROR(27);
pub const HSPERROR_HSPERR_NO_FUNCTION_PARAMETERS: HSPERROR = HSPERROR(28);
pub const HSPERROR_HSPERR_STACK_OVERFLOW: HSPERROR = HSPERROR(29);
pub const HSPERROR_HSPERR_INVALID_PARAMETER: HSPERROR = HSPERROR(30);
pub const HSPERROR_HSPERR_INVALID_ARRAYSTORE: HSPERROR = HSPERROR(31);
pub const HSPERROR_HSPERR_INVALID_FUNCPARAM: HSPERROR = HSPERROR(32);
pub const HSPERROR_HSPERR_WINDOW_OBJECT_FULL: HSPERROR = HSPERROR(33);
pub const HSPERROR_HSPERR_INVALID_ARRAY: HSPERROR = HSPERROR(34);
pub const HSPERROR_HSPERR_STRUCT_REQUIRED: HSPERROR = HSPERROR(35);
pub const HSPERROR_HSPERR_INVALID_STRUCT_SOURCE: HSPERROR = HSPERROR(36);
pub const HSPERROR_HSPERR_INVALID_TYPE: HSPERROR = HSPERROR(37);
pub const HSPERROR_HSPERR_DLL_ERROR: HSPERROR = HSPERROR(38);
pub const HSPERROR_HSPERR_COMDLL_ERROR: HSPERROR = HSPERROR(39);
pub const HSPERROR_HSPERR_NORETVAL: HSPERROR = HSPERROR(40);
pub const HSPERROR_HSPERR_FUNCTION_SYNTAX: HSPERROR = HSPERROR(41);
pub const HSPERROR_HSPERR_INVALID_CALLBACK: HSPERROR = HSPERROR(42);
pub const HSPERROR_HSPERR_INTJUMP: HSPERROR = HSPERROR(43);
pub const HSPERROR_HSPERR_EXITRUN: HSPERROR = HSPERROR(44);
pub const HSPERROR_HSPERR_MAX: HSPERROR = HSPERROR(45);
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct HSPERROR(pub ::std::os::raw::c_int);
pub const DEBUGINFO_GENERAL: _bindgen_ty_2 = _bindgen_ty_2(0);
pub const DEBUGINFO_VARNAME: _bindgen_ty_2 = _bindgen_ty_2(1);
pub const DEBUGINFO_INTINFO: _bindgen_ty_2 = _bindgen_ty_2(2);
pub const DEBUGINFO_GRINFO: _bindgen_ty_2 = _bindgen_ty_2(3);
pub const DEBUGINFO_MMINFO: _bindgen_ty_2 = _bindgen_ty_2(4);
pub const DEBUGINFO_MAX: _bindgen_ty_2 = _bindgen_ty_2(5);
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct _bindgen_ty_2(pub ::std::os::raw::c_int);
pub const HSPDEBUG_NONE: _bindgen_ty_3 = _bindgen_ty_3(0);
pub const HSPDEBUG_RUN: _bindgen_ty_3 = _bindgen_ty_3(1);
pub const HSPDEBUG_STOP: _bindgen_ty_3 = _bindgen_ty_3(2);
pub const HSPDEBUG_STEPIN: _bindgen_ty_3 = _bindgen_ty_3(3);
pub const HSPDEBUG_STEPOVER: _bindgen_ty_3 = _bindgen_ty_3(4);
pub const HSPDEBUG_MAX: _bindgen_ty_3 = _bindgen_ty_3(5);
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct _bindgen_ty_3(pub ::std::os::raw::c_int);
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct HSP3DEBUG {
    pub flag: ::std::os::raw::c_int,
    pub line: ::std::os::raw::c_int,
    pub fname: *mut ::std::os::raw::c_char,
    pub dbgwin: *mut ::std::os::raw::c_void,
    pub dbgval: *mut ::std::os::raw::c_char,
    pub hspctx: *mut HSPCTX,
    pub get_value: ::std::option::Option<
        unsafe extern "C-unwind" fn(arg1: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_char,
    >,
    pub get_varinf: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            arg1: *mut ::std::os::raw::c_char,
            arg2: ::std::os::raw::c_int,
        ) -> *mut ::std::os::raw::c_char,
    >,
    pub dbg_close: ::std::option::Option<unsafe extern "C-unwind" fn(arg1: *mut ::std::os::raw::c_char)>,
    pub dbg_curinf: ::std::option::Option<unsafe extern "C-unwind" fn()>,
    pub dbg_set: ::std::option::Option<
        unsafe extern "C-unwind" fn(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >,
    pub dbg_callstack: ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut ::std::os::raw::c_char>,
}
impl Default for HSP3DEBUG {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct HSPHED {
    pub h1: ::std::os::raw::c_char,
    pub h2: ::std::os::raw::c_char,
    pub h3: ::std::os::raw::c_char,
    pub h4: ::std::os::raw::c_char,
    pub version: ::std::os::raw::c_int,
    pub max_val: ::std::os::raw::c_int,
    pub allsize: ::std::os::raw::c_int,
    pub pt_cs: ::std::os::raw::c_int,
    pub max_cs: ::std::os::raw::c_int,
    pub pt_ds: ::std::os::raw::c_int,
    pub max_ds: ::std::os::raw::c_int,
    pub pt_ot: ::std::os::raw::c_int,
    pub max_ot: ::std::os::raw::c_int,
    pub pt_dinfo: ::std::os::raw::c_int,
    pub max_dinfo: ::std::os::raw::c_int,
    pub pt_linfo: ::std::os::raw::c_int,
    pub max_linfo: ::std::os::raw::c_int,
    pub pt_finfo: ::std::os::raw::c_int,
    pub max_finfo: ::std::os::raw::c_int,
    pub pt_minfo: ::std::os::raw::c_int,
    pub max_minfo: ::std::os::raw::c_int,
    pub pt_finfo2: ::std::os::raw::c_int,
    pub max_finfo2: ::std::os::raw::c_int,
    pub pt_hpidat: ::std::os::raw::c_int,
    pub max_hpi: ::std::os::raw::c_short,
    pub max_varhpi: ::std::os::raw::c_short,
    pub bootoption: ::std::os::raw::c_int,
    pub runtime: ::std::os::raw::c_int,
    pub pt_sr: ::std::os::raw::c_int,
    pub max_sr: ::std::os::raw::c_int,
    pub pt_exopt: ::std::os::raw::c_int,
    pub max_exopt: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct MEM_HPIDAT {
    pub flag: ::std::os::raw::c_short,
    pub option: ::std::os::raw::c_short,
    pub libname: ::std::os::raw::c_int,
    pub funcname: ::std::os::raw::c_int,
    pub libptr: *mut ::std::os::raw::c_void,
}
impl Default for MEM_HPIDAT {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type HPIDAT = MEM_HPIDAT;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct LIBDAT {
    pub flag: ::std::os::raw::c_int,
    pub nameidx: ::std::os::raw::c_int,
    pub hlib: *mut ::std::os::raw::c_void,
    pub clsid: ::std::os::raw::c_int,
}
impl Default for LIBDAT {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type HED_LIBDAT = LIBDAT;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct STRUCTPRM {
    pub mptype: ::std::os::raw::c_short,
    pub subid: ::std::os::raw::c_short,
    pub offset: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct STRUCTDAT {
    pub index: ::std::os::raw::c_short,
    pub subid: ::std::os::raw::c_short,
    pub prmindex: ::std::os::raw::c_int,
    pub prmmax: ::std::os::raw::c_int,
    pub nameidx: ::std::os::raw::c_int,
    pub size: ::std::os::raw::c_int,
    pub otindex: ::std::os::raw::c_int,
    pub __bindgen_anon_1: STRUCTDAT__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union STRUCTDAT__bindgen_ty_1 {
    pub proc_: *mut ::std::os::raw::c_void,
    pub funcflag: ::std::os::raw::c_int,
}
impl Default for STRUCTDAT__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl ::std::fmt::Debug for STRUCTDAT__bindgen_ty_1 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, "STRUCTDAT__bindgen_ty_1 {{ union }}")
    }
}
impl Default for STRUCTDAT {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl ::std::fmt::Debug for STRUCTDAT {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write ! (f , "STRUCTDAT {{ index: {:?}, subid: {:?}, prmindex: {:?}, prmmax: {:?}, nameidx: {:?}, size: {:?}, otindex: {:?}, __bindgen_anon_1: {:?} }}" , self . index , self . subid , self . prmindex , self . prmmax , self . nameidx , self . size , self . otindex , self . __bindgen_anon_1)
    }
}
pub type HED_STRUCTDAT = STRUCTDAT;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct MPVarData {
    pub pval: *mut PVal,
    pub aptr: APTR,
}
impl Default for MPVarData {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct MPModVarData {
    pub subid: ::std::os::raw::c_short,
    pub magic: ::std::os::raw::c_short,
    pub pval: *mut PVal,
    pub aptr: APTR,
}
impl Default for MPModVarData {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct IRQDAT {
    pub flag: ::std::os::raw::c_short,
    pub opt: ::std::os::raw::c_short,
    pub custom: ::std::os::raw::c_int,
    pub custom2: ::std::os::raw::c_int,
    pub iparam: ::std::os::raw::c_int,
    pub ptr: *mut ::std::os::raw::c_ushort,
    pub callback: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            arg1: *mut IRQDAT,
            arg2: ::std::os::raw::c_int,
            arg3: ::std::os::raw::c_int,
        ),
    >,
}
impl Default for IRQDAT {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct HSPEXINFO30 {
    pub ver: ::std::os::raw::c_short,
    pub min: ::std::os::raw::c_short,
    pub er: *mut ::std::os::raw::c_int,
    pub pstr: *mut ::std::os::raw::c_char,
    pub stmp: *mut ::std::os::raw::c_char,
    pub mpval: *mut *mut PVal,
    pub actscr: *mut ::std::os::raw::c_int,
    pub nptype: *mut ::std::os::raw::c_int,
    pub npval: *mut ::std::os::raw::c_int,
    pub strsize: *mut ::std::os::raw::c_int,
    pub refstr: *mut ::std::os::raw::c_char,
    pub HspFunc_prm_getv:
        ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut ::std::os::raw::c_void>,
    pub HspFunc_prm_geti: ::std::option::Option<unsafe extern "C-unwind" fn() -> ::std::os::raw::c_int>,
    pub HspFunc_prm_getdi: ::std::option::Option<
        unsafe extern "C-unwind" fn(defval: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_prm_gets:
        ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut ::std::os::raw::c_char>,
    pub HspFunc_prm_getds: ::std::option::Option<
        unsafe extern "C-unwind" fn(defstr: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char,
    >,
    pub HspFunc_val_realloc: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            pv: *mut PVal,
            size: ::std::os::raw::c_int,
            mode: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_fread: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            fname: *mut ::std::os::raw::c_char,
            readmem: *mut ::std::os::raw::c_void,
            rlen: ::std::os::raw::c_int,
            seekofs: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_fsize: ::std::option::Option<
        unsafe extern "C-unwind" fn(fname: *mut ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_getbmscr: ::std::option::Option<
        unsafe extern "C-unwind" fn(wid: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_void,
    >,
    pub HspFunc_getobj: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            wid: ::std::os::raw::c_int,
            id: ::std::os::raw::c_int,
            inf: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_setobj: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            wid: ::std::os::raw::c_int,
            id: ::std::os::raw::c_int,
            inf: *const ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub npexflg: *mut ::std::os::raw::c_int,
    pub hspctx: *mut HSPCTX,
    pub HspFunc_addobj: ::std::option::Option<
        unsafe extern "C-unwind" fn(wid: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_puterror: ::std::option::Option<unsafe extern "C-unwind" fn(error: HSPERROR)>,
    pub HspFunc_getproc: ::std::option::Option<
        unsafe extern "C-unwind" fn(type_: ::std::os::raw::c_int) -> *mut HspVarProc,
    >,
    pub HspFunc_seekproc: ::std::option::Option<
        unsafe extern "C-unwind" fn(name: *const ::std::os::raw::c_char) -> *mut HspVarProc,
    >,
    pub HspFunc_prm_next: ::std::option::Option<unsafe extern "C-unwind" fn()>,
    pub HspFunc_prm_get: ::std::option::Option<unsafe extern "C-unwind" fn() -> ::std::os::raw::c_int>,
    pub HspFunc_prm_getd: ::std::option::Option<unsafe extern "C-unwind" fn() -> f64>,
    pub HspFunc_prm_getdd: ::std::option::Option<unsafe extern "C-unwind" fn(defval: f64) -> f64>,
    pub HspFunc_prm_getlb:
        ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut ::std::os::raw::c_ushort>,
    pub HspFunc_prm_getpval: ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut PVal>,
    pub HspFunc_prm_getva:
        ::std::option::Option<unsafe extern "C-unwind" fn(pval: *mut *mut PVal) -> APTR>,
    pub HspFunc_prm_setva: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            pval: *mut PVal,
            aptr: APTR,
            type_: ::std::os::raw::c_int,
            ptr: *const ::std::os::raw::c_void,
        ),
    >,
    pub HspFunc_malloc: ::std::option::Option<
        unsafe extern "C-unwind" fn(size: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_char,
    >,
    pub HspFunc_free: ::std::option::Option<unsafe extern "C-unwind" fn(ptr: *mut ::std::os::raw::c_void)>,
    pub HspFunc_expand: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            ptr: *mut ::std::os::raw::c_char,
            size: ::std::os::raw::c_int,
        ) -> *mut ::std::os::raw::c_char,
    >,
    pub HspFunc_addirq: ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut IRQDAT>,
    pub HspFunc_hspevent: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            event: ::std::os::raw::c_int,
            prm1: ::std::os::raw::c_int,
            prm2: ::std::os::raw::c_int,
            prm3: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_registvar: ::std::option::Option<
        unsafe extern "C-unwind" fn(flag: ::std::os::raw::c_int, func: HSPVAR_COREFUNC),
    >,
    pub HspFunc_setpc:
        ::std::option::Option<unsafe extern "C-unwind" fn(pc: *const ::std::os::raw::c_ushort)>,
    pub HspFunc_call:
        ::std::option::Option<unsafe extern "C-unwind" fn(pc: *const ::std::os::raw::c_ushort)>,
    pub HspFunc_mref:
        ::std::option::Option<unsafe extern "C-unwind" fn(pval: *mut PVal, prm: ::std::os::raw::c_int)>,
    pub HspFunc_dim: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            pval: *mut PVal,
            flag: ::std::os::raw::c_int,
            len0: ::std::os::raw::c_int,
            len1: ::std::os::raw::c_int,
            len2: ::std::os::raw::c_int,
            len3: ::std::os::raw::c_int,
            len4: ::std::os::raw::c_int,
        ),
    >,
    pub HspFunc_redim: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            pval: *mut PVal,
            lenid: ::std::os::raw::c_int,
            len: ::std::os::raw::c_int,
        ),
    >,
    pub HspFunc_array:
        ::std::option::Option<unsafe extern "C-unwind" fn(pval: *mut PVal, offset: ::std::os::raw::c_int)>,
}
impl Default for HSPEXINFO30 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct HSPEXINFO {
    pub ver: ::std::os::raw::c_short,
    pub min: ::std::os::raw::c_short,
    pub er: *mut ::std::os::raw::c_int,
    pub pstr: *mut ::std::os::raw::c_char,
    pub stmp: *mut ::std::os::raw::c_char,
    pub mpval: *mut *mut PVal,
    pub actscr: *mut ::std::os::raw::c_int,
    pub nptype: *mut ::std::os::raw::c_int,
    pub npval: *mut ::std::os::raw::c_int,
    pub strsize: *mut ::std::os::raw::c_int,
    pub refstr: *mut ::std::os::raw::c_char,
    pub HspFunc_prm_getv:
        ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut ::std::os::raw::c_void>,
    pub HspFunc_prm_geti: ::std::option::Option<unsafe extern "C-unwind" fn() -> ::std::os::raw::c_int>,
    pub HspFunc_prm_getdi: ::std::option::Option<
        unsafe extern "C-unwind" fn(defval: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_prm_gets:
        ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut ::std::os::raw::c_char>,
    pub HspFunc_prm_getds: ::std::option::Option<
        unsafe extern "C-unwind" fn(defstr: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char,
    >,
    pub HspFunc_val_realloc: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            pv: *mut PVal,
            size: ::std::os::raw::c_int,
            mode: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_fread: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            fname: *mut ::std::os::raw::c_char,
            readmem: *mut ::std::os::raw::c_void,
            rlen: ::std::os::raw::c_int,
            seekofs: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_fsize: ::std::option::Option<
        unsafe extern "C-unwind" fn(fname: *mut ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_getbmscr: ::std::option::Option<
        unsafe extern "C-unwind" fn(wid: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_void,
    >,
    pub HspFunc_getobj: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            wid: ::std::os::raw::c_int,
            id: ::std::os::raw::c_int,
            inf: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_setobj: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            wid: ::std::os::raw::c_int,
            id: ::std::os::raw::c_int,
            inf: *const ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub npexflg: *mut ::std::os::raw::c_int,
    pub hspctx: *mut HSPCTX,
    pub HspFunc_addobj: ::std::option::Option<
        unsafe extern "C-unwind" fn(wid: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_puterror: ::std::option::Option<unsafe extern "C-unwind" fn(error: HSPERROR)>,
    pub HspFunc_getproc: ::std::option::Option<
        unsafe extern "C-unwind" fn(type_: ::std::os::raw::c_int) -> *mut HspVarProc,
    >,
    pub HspFunc_seekproc: ::std::option::Option<
        unsafe extern "C-unwind" fn(name: *const ::std::os::raw::c_char) -> *mut HspVarProc,
    >,
    pub HspFunc_prm_next: ::std::option::Option<unsafe extern "C-unwind" fn()>,
    pub HspFunc_prm_get: ::std::option::Option<unsafe extern "C-unwind" fn() -> ::std::os::raw::c_int>,
    pub HspFunc_prm_getd: ::std::option::Option<unsafe extern "C-unwind" fn() -> f64>,
    pub HspFunc_prm_getdd: ::std::option::Option<unsafe extern "C-unwind" fn(defval: f64) -> f64>,
    pub HspFunc_prm_getlb:
        ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut ::std::os::raw::c_ushort>,
    pub HspFunc_prm_getpval: ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut PVal>,
    pub HspFunc_prm_getva:
        ::std::option::Option<unsafe extern "C-unwind" fn(pval: *mut *mut PVal) -> APTR>,
    pub HspFunc_prm_setva: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            pval: *mut PVal,
            aptr: APTR,
            type_: ::std::os::raw::c_int,
            ptr: *const ::std::os::raw::c_void,
        ),
    >,
    pub HspFunc_malloc: ::std::option::Option<
        unsafe extern "C-unwind" fn(size: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_char,
    >,
    pub HspFunc_free: ::std::option::Option<unsafe extern "C-unwind" fn(ptr: *mut ::std::os::raw::c_void)>,
    pub HspFunc_expand: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            ptr: *mut ::std::os::raw::c_char,
            size: ::std::os::raw::c_int,
        ) -> *mut ::std::os::raw::c_char,
    >,
    pub HspFunc_addirq: ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut IRQDAT>,
    pub HspFunc_hspevent: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            event: ::std::os::raw::c_int,
            prm1: ::std::os::raw::c_int,
            prm2: ::std::os::raw::c_int,
            prm3: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_registvar: ::std::option::Option<
        unsafe extern "C-unwind" fn(flag: ::std::os::raw::c_int, func: HSPVAR_COREFUNC),
    >,
    pub HspFunc_setpc:
        ::std::option::Option<unsafe extern "C-unwind" fn(pc: *const ::std::os::raw::c_ushort)>,
    pub HspFunc_call:
        ::std::option::Option<unsafe extern "C-unwind" fn(pc: *const ::std::os::raw::c_ushort)>,
    pub HspFunc_mref:
        ::std::option::Option<unsafe extern "C-unwind" fn(pval: *mut PVal, prm: ::std::os::raw::c_int)>,
    pub HspFunc_dim: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            pval: *mut PVal,
            flag: ::std::os::raw::c_int,
            len0: ::std::os::raw::c_int,
            len1: ::std::os::raw::c_int,
            len2: ::std::os::raw::c_int,
            len3: ::std::os::raw::c_int,
            len4: ::std::os::raw::c_int,
        ),
    >,
    pub HspFunc_redim: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            pval: *mut PVal,
            lenid: ::std::os::raw::c_int,
            len: ::std::os::raw::c_int,
        ),
    >,
    pub HspFunc_array:
        ::std::option::Option<unsafe extern "C-unwind" fn(pval: *mut PVal, offset: ::std::os::raw::c_int)>,
    pub HspFunc_varname: ::std::option::Option<
        unsafe extern "C-unwind" fn(id: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_char,
    >,
    pub HspFunc_seekvar: ::std::option::Option<
        unsafe extern "C-unwind" fn(name: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub HspFunc_prm_getns:
        ::std::option::Option<unsafe extern "C-unwind" fn() -> *mut ::std::os::raw::c_char>,
    pub HspFunc_prm_getnds: ::std::option::Option<
        unsafe extern "C-unwind" fn(defstr: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char,
    >,
}
impl Default for HSPEXINFO {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct LOOPDAT {
    pub time: ::std::os::raw::c_int,
    pub cnt: ::std::os::raw::c_int,
    pub step: ::std::os::raw::c_int,
    pub pt: *mut ::std::os::raw::c_ushort,
}
impl Default for LOOPDAT {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const RUNMODE_RUN: _bindgen_ty_4 = _bindgen_ty_4(0);
pub const RUNMODE_WAIT: _bindgen_ty_4 = _bindgen_ty_4(1);
pub const RUNMODE_AWAIT: _bindgen_ty_4 = _bindgen_ty_4(2);
pub const RUNMODE_STOP: _bindgen_ty_4 = _bindgen_ty_4(3);
pub const RUNMODE_END: _bindgen_ty_4 = _bindgen_ty_4(4);
pub const RUNMODE_ERROR: _bindgen_ty_4 = _bindgen_ty_4(5);
pub const RUNMODE_RETURN: _bindgen_ty_4 = _bindgen_ty_4(6);
pub const RUNMODE_INTJUMP: _bindgen_ty_4 = _bindgen_ty_4(7);
pub const RUNMODE_ASSERT: _bindgen_ty_4 = _bindgen_ty_4(8);
pub const RUNMODE_LOGMES: _bindgen_ty_4 = _bindgen_ty_4(9);
pub const RUNMODE_EXITRUN: _bindgen_ty_4 = _bindgen_ty_4(10);
pub const RUNMODE_RESTART: _bindgen_ty_4 = _bindgen_ty_4(11);
pub const RUNMODE_MAX: _bindgen_ty_4 = _bindgen_ty_4(12);
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct _bindgen_ty_4(pub ::std::os::raw::c_int);
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, PartialEq)]
pub struct HSPCTX {
    pub hsphed: *mut HSPHED,
    pub mcs: *mut ::std::os::raw::c_ushort,
    pub mem_mcs: *mut ::std::os::raw::c_ushort,
    pub mem_mds: *mut ::std::os::raw::c_char,
    pub mem_di: *mut ::std::os::raw::c_uchar,
    pub mem_ot: *mut ::std::os::raw::c_int,
    pub mem_irq: *mut IRQDAT,
    pub irqmax: ::std::os::raw::c_int,
    pub iparam: ::std::os::raw::c_int,
    pub wparam: ::std::os::raw::c_int,
    pub lparam: ::std::os::raw::c_int,
    pub mem_var: *mut PVal,
    pub exinfo: HSPEXINFO30,
    pub runmode: ::std::os::raw::c_int,
    pub waitcount: ::std::os::raw::c_int,
    pub waitbase: ::std::os::raw::c_int,
    pub waittick: ::std::os::raw::c_int,
    pub lasttick: ::std::os::raw::c_int,
    pub sublev: ::std::os::raw::c_int,
    pub mem_loop: [LOOPDAT; 32usize],
    pub looplev: ::std::os::raw::c_int,
    pub err: HSPERROR,
    pub hspstat: ::std::os::raw::c_int,
    pub stat: ::std::os::raw::c_int,
    pub strsize: ::std::os::raw::c_int,
    pub refstr: *mut ::std::os::raw::c_char,
    pub fnbuffer: *mut ::std::os::raw::c_char,
    pub instance: *mut ::std::os::raw::c_void,
    pub intwnd_id: ::std::os::raw::c_int,
    pub note_pval: *mut PVal,
    pub note_aptr: APTR,
    pub notep_pval: *mut PVal,
    pub notep_aptr: APTR,
    pub stmp: *mut ::std::os::raw::c_char,
    pub prmstack: *mut ::std::os::raw::c_void,
    pub mem_linfo: *mut LIBDAT,
    pub mem_minfo: *mut STRUCTPRM,
    pub mem_finfo: *mut STRUCTDAT,
    pub retval_level: ::std::os::raw::c_int,
    pub endcode: ::std::os::raw::c_int,
    pub msgfunc: ::std::option::Option<unsafe extern "C-unwind" fn(arg1: *mut HSPCTX)>,
    pub wnd_parent: *mut ::std::os::raw::c_void,
    pub refdval: f64,
    pub cmdline: *mut ::std::os::raw::c_char,
    pub exinfo2: *mut HSPEXINFO,
    pub prmstack_max: ::std::os::raw::c_int,
    pub dsindex: *mut ::std::os::raw::c_int,
    pub dsindex_size: ::std::os::raw::c_int,
    pub language: ::std::os::raw::c_int,
    pub callback_flag: ::std::os::raw::c_int,
    pub modfilename: *mut ::std::os::raw::c_char,
    pub tvfoldername: *mut ::std::os::raw::c_char,
    pub homefoldername: *mut ::std::os::raw::c_char,
    pub langcode: [::std::os::raw::c_char; 4usize],
}
impl Default for HSPCTX {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct HSPROUTINE {
    pub stacklev: ::std::os::raw::c_int,
    pub mcsret: *mut ::std::os::raw::c_ushort,
    pub param: *mut STRUCTDAT,
    pub oldtack: *mut ::std::os::raw::c_void,
    pub oldlev: ::std::os::raw::c_int,
}
impl Default for HSPROUTINE {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type HSP3_CMDFUNC = ::std::option::Option<
    unsafe extern "C-unwind" fn(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
>;
pub type HSP3_REFFUNC = ::std::option::Option<
    unsafe extern "C-unwind" fn(
        arg1: *mut ::std::os::raw::c_int,
        arg2: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void,
>;
pub type HSP3_TERMFUNC = ::std::option::Option<
    unsafe extern "C-unwind" fn(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
>;
pub type HSP3_MSGFUNC = ::std::option::Option<
    unsafe extern "C-unwind" fn(
        arg1: ::std::os::raw::c_int,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
pub type HSP3_EVENTFUNC = ::std::option::Option<
    unsafe extern "C-unwind" fn(
        arg1: ::std::os::raw::c_int,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, Ord, PartialEq, Eq)]
pub struct HSP3TYPEINFO {
    pub type_: ::std::os::raw::c_short,
    pub option: ::std::os::raw::c_short,
    pub hspctx: *mut HSPCTX,
    pub hspexinfo: *mut HSPEXINFO,
    pub cmdfunc: ::std::option::Option<
        unsafe extern "C-unwind" fn(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >,
    pub reffunc: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            arg1: *mut ::std::os::raw::c_int,
            arg2: ::std::os::raw::c_int,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub termfunc: ::std::option::Option<
        unsafe extern "C-unwind" fn(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >,
    pub msgfunc: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            arg1: ::std::os::raw::c_int,
            arg2: ::std::os::raw::c_int,
            arg3: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub eventfunc: ::std::option::Option<
        unsafe extern "C-unwind" fn(
            arg1: ::std::os::raw::c_int,
            arg2: ::std::os::raw::c_int,
            arg3: ::std::os::raw::c_int,
            arg4: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
}
impl Default for HSP3TYPEINFO {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const HSPIRQ_ONEXIT: _bindgen_ty_5 = _bindgen_ty_5(0);
pub const HSPIRQ_ONERROR: _bindgen_ty_5 = _bindgen_ty_5(1);
pub const HSPIRQ_ONKEY: _bindgen_ty_5 = _bindgen_ty_5(2);
pub const HSPIRQ_ONCLICK: _bindgen_ty_5 = _bindgen_ty_5(3);
pub const HSPIRQ_USERDEF: _bindgen_ty_5 = _bindgen_ty_5(4);
pub const HSPIRQ_MAX: _bindgen_ty_5 = _bindgen_ty_5(5);
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct _bindgen_ty_5(pub ::std::os::raw::c_int);
pub const HSPEVENT_NONE: _bindgen_ty_6 = _bindgen_ty_6(0);
pub const HSPEVENT_COMMAND: _bindgen_ty_6 = _bindgen_ty_6(1);
pub const HSPEVENT_HSPIRQ: _bindgen_ty_6 = _bindgen_ty_6(2);
pub const HSPEVENT_GETKEY: _bindgen_ty_6 = _bindgen_ty_6(3);
pub const HSPEVENT_STICK: _bindgen_ty_6 = _bindgen_ty_6(4);
pub const HSPEVENT_FNAME: _bindgen_ty_6 = _bindgen_ty_6(5);
pub const HSPEVENT_FREAD: _bindgen_ty_6 = _bindgen_ty_6(6);
pub const HSPEVENT_FWRITE: _bindgen_ty_6 = _bindgen_ty_6(7);
pub const HSPEVENT_FEXIST: _bindgen_ty_6 = _bindgen_ty_6(8);
pub const HSPEVENT_FDELETE: _bindgen_ty_6 = _bindgen_ty_6(9);
pub const HSPEVENT_FMKDIR: _bindgen_ty_6 = _bindgen_ty_6(10);
pub const HSPEVENT_FCHDIR: _bindgen_ty_6 = _bindgen_ty_6(11);
pub const HSPEVENT_FCOPY: _bindgen_ty_6 = _bindgen_ty_6(12);
pub const HSPEVENT_FDIRLIST1: _bindgen_ty_6 = _bindgen_ty_6(13);
pub const HSPEVENT_FDIRLIST2: _bindgen_ty_6 = _bindgen_ty_6(14);
pub const HSPEVENT_GETPICSIZE: _bindgen_ty_6 = _bindgen_ty_6(15);
pub const HSPEVENT_PICLOAD: _bindgen_ty_6 = _bindgen_ty_6(16);
pub const HSPEVENT_MAX: _bindgen_ty_6 = _bindgen_ty_6(17);
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct _bindgen_ty_6(pub ::std::os::raw::c_int);
